### ISSUE TITLE
AVI Not working

### ISSUE THREAD

**Issue by gecatalin** [ArouG/AVIInfo.js#1]
Well hi, it's me again 💃 
Tried this: https://archive.org/download/Test_Avi/MVI_0043.AVI

got: av2.js:793 Uncaught RangeError: Offset is outside the bounds of the DataView

**Comment by ArouG** [comment]
Aîe !! I've work ...
OK, thanks again.

**Comment by ArouG** [comment]
After some years ( :-))) repaired by "suppress" of one line : obj.cbSize DO NOT interest here. In fact, I should test the buffer.byteLength and define cdSize only if buffer.byteLength > 16
